version: '3.0'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    security_opt:
      - "seccomp:unconfined"
    cap_add:
      - SYS_PTRACE
    command: sh -c 'go build -gcflags "all=-N -l" -o /server && /go/bin/dlv --headless --listen=0.0.0.0:40000 --api-version=2 exec /server'
#    command: sh -c 'go build -o /server && /server'
    ports:
      - "3000:3000"
      - "40000:40000"
    links:
      - postgres
    depends_on:
      - postgres
    volumes:
      - .:/src
  postgres:
    image: postgres:12-alpine
    ports:
      - "5442:5432"
    environment:
      POSTGRES_USER: syssat
      POSTGRES_PASSWORD: syssat
      POSTGRES_DB: syssat